### ISSUE TITLE
replaceMap contains wrong default values

### ISSUE THREAD

**Issue by smaren** [teppeis/fixclosure#245]
The `replaceMap` contains a value from `goog.disposeAll` to `goog.dispose`. However, `goog.disposable` provides `goog.disposeAll` so it should not be changed to something different. Is the `replaceMap` relevant at all if you are using a deps file? I think it is a similar case to `providedNamespaces` which is now deprecated in favor of `--depsJs`.

**Comment by teppeis** [comment]
`goog.disposeAll` should be removed from `replaceMap` because it's `goog.provide`d now (https://github.com/google/closure-library/commit/6d57246).

`depsJs` almost deprecated `replaceMap`, but some special namespaces still needed `replaceMap`. `goog.disposeAll` or `goog.dom.$F` didn't share the prefix with provided namespace. But Closure Library has fixed or removed them. So now `replaceMap` is completely deprecated.
